#pragma once

typedef enum {
    SubGhzCustomEventManagerNoSet = 0,
    SubGhzCustomEventManagerSet,
    SubGhzCustomEventManagerSetRAW,

    //SubGhzCustomEvent
    SubGhzCustomEventSceneDeleteSuccess = 100,
    SubGhzCustomEventSceneDelete,
    SubGhzCustomEventSceneDeleteBack,
    SubGhzCustomEventSceneDeleteRAW,
    SubGhzCustomEventSceneDeleteRAWBack,

    SubGhzCustomEventSceneReceiverInfoTxStart,
    SubGhzCustomEventSceneReceiverInfoTxStop,
    SubGhzCustomEventSceneReceiverInfoSave,
    SubGhzCustomEventSceneSaveName,
    SubGhzCustomEventSceneSignalSettings,
    SubGhzCustomEventSceneSaveSuccess,
    SubGhzCustomEventSceneShowErrorBack,
    SubGhzCustomEventSceneShowErrorOk,
    SubGhzCustomEventSceneShowErrorSub,
    SubGhzCustomEventSceneShowOnlyRX,
    SubGhzCustomEventSceneAnalyzerLock,
    SubGhzCustomEventSceneAnalyzerUnlock,
    SubGhzCustomEventSceneSettingLock,
    SubGhzCustomEventSceneSettingResetToDefault,

    SubGhzCustomEventSceneExit,
    SubGhzCustomEventSceneStay,

    SubGhzCustomEventSceneRpcLoad,
    SubGhzCustomEventSceneRpcButtonPress,
    SubGhzCustomEventSceneRpcButtonRelease,
    SubGhzCustomEventSceneRpcButtonPressRelease,
    SubGhzCustomEventSceneRpcSessionClose,

    SubGhzCustomEventViewReceiverOK,
    SubGhzCustomEventViewReceiverConfig,
    SubGhzCustomEventViewReceiverBack,
    SubGhzCustomEventViewReceiverOffDisplay,
    SubGhzCustomEventViewReceiverUnlock,
    SubGhzCustomEventViewReceiverDeleteItem,

    SubGhzCustomEventViewReadRAWBack,
    SubGhzCustomEventViewReadRAWIDLE,
    SubGhzCustomEventViewReadRAWREC,
    SubGhzCustomEventViewReadRAWConfig,
    SubGhzCustomEventViewReadRAWErase,
    SubGhzCustomEventViewReadRAWSendStart,
    SubGhzCustomEventViewReadRAWSendStop,
    SubGhzCustomEventViewReadRAWSave,
    SubGhzCustomEventViewReadRAWTXRXStop,
    SubGhzCustomEventViewReadRAWMore,

    SubGhzCustomEventViewTransmitterBack,
    SubGhzCustomEventViewTransmitterSendStart,
    SubGhzCustomEventViewTransmitterSendStop,
    SubGhzCustomEventViewTransmitterError,

    SubGhzCustomEventViewFreqAnalOkShort,
    SubGhzCustomEventViewFreqAnalOkLong,

    SubGhzCustomEventByteInputDone,
} SubGhzCustomEvent;

typedef enum {
    SetTypeFaacSLH_868,
    SetTypeFaacSLH_433,
    SetTypeBFTMitto,
    SetTypeSomfyTelis,
    SetTypeKingGatesStylo4k,
    SetTypeBenincaARC,
    SetTypeJarolift,
    SetTypeANMotorsAT4,
    SetTypeAlutechAT4N,
    SetTypePhoenix_V2_433,
    SetTypeHCS101_433_92,
    SetTypeDoorHan_315_00,
    SetTypeDoorHan_433_92,
    SetTypeBeninca433,
    SetTypeBeninca868,
    SetTypeComunello433,
    SetTypeComunello868,
    SetTypeAllmatic433,
    SetTypeAllmatic868,
    SetTypeCenturion433,
    SetTypeMonarch433,
    SetTypeJollyMotors433,
    SetTypeMotorline433,
    SetTypeSommer_FM_434,
    SetTypeSommer_FM_868,
    SetTypeSommer_FM12K_434,
    SetTypeSommer_FM12K_868,
    SetTypeStilmatic,
    SetTypeIronLogic,
    SetTypeIronLogicSmart,
    SetTypeDeaMio433,
    SetTypeDTMNeo433,
    SetTypeGibidi433,
    SetTypeGSN,
    SetTypeAprimatic,
    SetTypeElmesElectronic,
    SetTypeNormstahl_433_92,
    SetTypeJCM_433_92,
    SetTypeNovoferm_433_92,
    SetTypeHormannEcoStar_433_92,
    SetTypeCardinS449_433FM,
    SetTypeFAACRCXT_433_92,
    SetTypeFAACRCXT_868,
    SetTypeGeniusBravo433,
    SetTypeNiceMHouse_433_92,
    SetTypeNiceSmilo_433_92,
    SetTypeNiceFlorS_433_92,
    SetTypeNiceOne_433_92,
    SetTypeNiceFlo12bit,
    SetTypeNiceFlo24bit,
    SetTypeCAME12bit,
    SetTypeCAME24bit,
    SetTypeCAME12bit868,
    SetTypeCAME24bit868,
    SetTypeCAMETwee,
    SetTypeCameAtomo433,
    SetTypeCameAtomo868,
    SetTypeCAMESpace,
    SetTypePricenton315,
    SetTypePricenton433,
    SetTypeZKTeco430,
    SetTypeBETT_433,
    SetTypeGangQi_433,
    SetTypeHollarm_433,
    SetTypeReversRB2_433,
    SetTypeMarantec24_868,
    SetTypeMarantec_433,
    SetTypeMarantec_868,
    SetTypeRoger_433,
    SetTypeLinear_300_00,
    // SetTypeNeroSketch, //Deleted in OFW
    // SetTypeNeroRadio, //Deleted in OFW
    SetTypeGateTX,
    SetTypeSecPlus_v1_315_00,
    SetTypeSecPlus_v1_390_00,
    SetTypeSecPlus_v1_433_00,
    SetTypeSecPlus_v2_310_00,
    SetTypeSecPlus_v2_315_00,
    SetTypeSecPlus_v2_390_00,
    SetTypeSecPlus_v2_433_00,

    // --- Car Protocols ---
    SetTypeVAGType1_433,    // VW NEW - AUT64 key 0
    SetTypeVAGType1Old_433,  // VW OLD - AUT64 key 0 (0xC0 type byte)
    SetTypeVAGType2_433,  // AUDI - TEA encryption
    SetTypeVAGType3_433,  // SEAT - AUT64 key 1
    SetTypeVAGType4_433,  // SKODA - AUT64 key 2
    SetTypePorscheCayenne_433,
    SetTypeFiatSPA_433,
    SetTypeFordV0_433,
    SetTypeKiaV0_433,
    SetTypeKiaV1_433,
    SetTypeKiaV2_433,
    SetTypeKiaV3_433,
    SetTypeKiaV4_433,
    SetTypeKiaV5_433,
    SetTypeKiaV6_433,
    SetTypeSubaru_433,
    SetTypeMazdaSiemens_433,
    SetTypeSuzuki_433,
    SetTypeMitsubishi_868,

    SetTypeMAX,
} SetType;
